// import "./globals.css";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import Login from "@/components/Login/Login";
// <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
//   <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
//   <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
//   <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
//   <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet"></link>
// import "@/"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // viewport:'1.0'
};
{
  /* <meta charset="utf-8">
  
  <title>FlexStart Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords"></meta> */
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"></meta>
      <link rel="preconnect" href="https://fonts.gstatic.com"></link>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"></link><link rel="stylesheet" href="" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet"></link>
    
        </head>
      <body>
        {children}
      </body>
    </html>
  );
}
