import "./globals.css";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";
// <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
//   <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
//   <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
//   <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
//   <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet"></link>
// import "@/"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // viewport:'1.0'
};
{
  /* <meta charset="utf-8">
  
  <title>FlexStart Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords"></meta> */
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"></meta>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"></link>
        </head>
      <body>{children}</body>
    </html>
  );
}
